version: '1.0'

services:
  php:
    build: ./php 
    ports:
      - "9000:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
    network:
      - test_network

  db:
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: TestDeploy
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - "9002:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - test_network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9001:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root1234
    depends_on:
      - db
    networks:
      - test_network

networks:
  test_network:
    driver: bridge