FROM php:8.4-apache

WORKDIR /var/www/html

RUN apt-get update && \
    apt-get install -y libzip-dev zip && \
    docker-php-ext-install pdo pdo_mysql zip

COPY . .

RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html

EXPOSE 80